### ISSUE TITLE
Provide NuGet package

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client.DependencyInjection#1]
Provide NuGet package so that we can mitigate the approach that was marked as obsolete in https://github.com/PrometheusClientNet/Prometheus.Client/releases/tag/4.0.0

**Comment by phnx47** [comment]
I prepared CI for deploy. We are waiting @sanych-sun for check my PR: #3

**Comment by phnx47** [comment]
First version: [v0.1.0](https://www.nuget.org/packages/Prometheus.Client.DependencyInjection/)
