### ISSUE TITLE
AddMetricFactory should use Metrics.DefaultCollectorRegistry unless specified otherwise

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client.DependencyInjection#2]
AddMetricFactory should use Metrics.DefaultCollectorRegistry unless specified otherwise because otherwise it breaks the integration with [`UsePrometheusServer`](https://github.com/PrometheusClientNet/Prometheus.Client.AspNetCore/blob/f4d2ef68522784782b3b30bfc12ee79b284a02cd/src/Prometheus.Client.AspNetCore/PrometheusExtensions.cs#L38)

**Comment by phnx47** [comment]
This is early version by @sanych-sun. I will make my correction.

**Comment by sanych-sun** [comment]
I think it will be better to do it in opposite direction. UsePrometheusServer should be updated to the following algorithm:
1) use the registry provided in options
2) try to resolve the registry from container
3) fallback to legacy static entry point

I'll update  Prometheus.Client.AspNetCore  and  Prometheus.Client.MetricServer  with this logic soon as well as examples.

**Comment by tomkerkhove** [comment]
Fine by me, but need something as it was not working 😅
